### ISSUE TITLE
Add support for nested selectors

### ISSUE THREAD

**Issue by aerni** [visuellverstehen/statamic-classify#12]
It would be great if this addon supported nested selectors like this:

```php
'p' => 'text-base',
'li p' => 'text-sm',
```

A valid use case are list elements, as Bard always adds another `<p>` tag inside an `<li>`.

**Comment by jonassiewertsen** [comment]
That's a great idea!

**Comment by jonassiewertsen** [comment]
I tinkered with some ideas yesterday and might be on the right track.

**Comment by aerni** [comment]
Nice! Let me know if you need me to test this.

**Comment by jonassiewertsen** [comment]
Thanks, I will. I started to fill up my regex toolbox with new knowledge, so it would be nice to check if it's working stable :-)

One step at a time. It might take a while before it's ready for testing.
