### ISSUE TITLE
Only first nested item gets classes

### ISSUE THREAD

**Issue by aerni** [visuellverstehen/statamic-classify#16]
I just encountered an issue where only the first `li` gets styled:

<img width="737" alt="Bildschirmfoto 2021-08-05 um 5 12 31 PM" src="https://user-images.githubusercontent.com/23167701/128374657-3732e143-7f6b-471b-b639-b6b29e076a5d.png">

I'm expecting all list items to have the classes `mt-2 first:mt-0` applied.

This is my config:
```php
'product' => [
    'h5' => 'mt-8 first:mt-0 text-xs uppercase tracking-wide font-medium text-indigo-500',
    'p'  => 'mt-4 first:mt-0 text-base leading-7 text-gray-800',
    'ul' => 'mt-4 first:mt-0 list-disc ml-8',
    'ul li' => 'mt-2 first:mt-0',
    'ul li p' => 'text-base leading-7 text-gray-800',
],
```

I'm on version 2.2.0.

**Comment by jonassiewertsen** [comment]
I can confirm the bug and did add a test as confirmation.

https://github.com/visuellverstehen/statamic-classify/pull/19
