### ISSUE TITLE
Feature request: get classes by name

### ISSUE THREAD

**Issue by ewhicher** [visuellverstehen/statamic-classify#30]
Just an idea, but it would be great to be able to get the classes individually, for example let's say you have this in your config:
```
'default' => [
    'h1' => 'headline',
    'a'  => 'link',
    'p' => 'paragraph',
],
```

If we could then use a tag to extract just the **h1** classes, something like:
`<h1 class="{{ classify:h1 }}">Heading</h1>`

I'm using tailwind, so to have `classify.php` as my 'source of truth' for all type styles would be super handy.

**Comment by simonolog** [comment]
I hope you haven't been waiting for this, but we eventually implemented this feature by adding a `classify` tag (essentially as proposed). You'll find more information in the (updated) readme.

**Comment by ewhicher** [comment]
I wouldn't say I was waiting on it, but am very glad it's here. Thanks 🙌
